export const productSpec = {
  defaultRules: {
    startingBalance: 10000,
    weeklyBonus: 2000,
    currencyName: 'Fantasy Dollars',
    cashValue: false,
    depositsEnabled: false,
    withdrawalsEnabled: false,
  },
  marketSets: [
    'World Cup',
    'NBA Playoffs',
    'Champions League',
    'Elections',
    'Awards / Entertainment',
  ],
  coreEntities: [
    'users',
    'leagues',
    'league_members',
    'market_sets',
    'league_market_sets',
    'events',
    'markets',
    'external_markets',
    'league_markets',
    'outcomes',
    'positions',
    'trades',
    'trade_intents',
    'market_price_history',
    'league_snapshots',
    'settlement_actions',
    'activity_feed',
  ],
}
